---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    provider: vmware_fusion
    box: precise64
    box_url: http://files.vagrantup.com/precise64_vmware.box
    require_chef_omnibus: true

suites:
- name: default
  run_list: ["recipe[apt]","recipe[java]","recipe[logstash]"]
  attributes: {}
